org: yaritzalopez
service: orders-serverless

provider:
  name: aws
  runtime: python3.13
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::157918330129:role/LabRole
  environment:
    TABLE_NAME: ${sls:stage}-t_orders

functions:
  createOrder:
    handler: createOrder.lambda_handler
    events:
      - http:
          path: /orders/{tenant_id}/create
          method: post
          cors: true
          integration: lambda

  listActiveOrders:
    handler: getActiveOrders.lambda_handler
    events:
      - http:
          path: /orders/{tenant_id}
          method: get
          cors: true
          integration: lambda

  updateStatus:
    handler: updateStatus.lambda_handler
    events:
      - http:
          path: /orders/{tenant_id}/{order_id}/updateStatus
          method: put
          cors: true
          integration: lambda

  cancelOrder:
    handler: cancelOrder.lambda_handler
    events:
      - http:
          path: /orders/{tenant_id}/{order_id}/cancel
          method: post
          cors: true
          integration: lambda

resources:
  Resources:
    TablaOrders:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: order_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: order_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
